- README.md
The example creates an alias which is never used after that.
> Use the key alias in README

- Dockerfile
add ```ENV GO111MODULE=on``` to Dockerfile to be able to create docker image.
> enable gomodules to fix docker image creation

- KOPS.md
- README.md
Added additional documentation to setup the encryption provider at cluster creation using kops. Please let me know if everything make sense or if there are things that you disagree with! This PR is trying to resolve #29. @micahhausler
> Add additional docs for kops bootstrap 

- KOPS.md
- README.md
According to documentation kube-apiserver does not have flag 'encryption-provider', but rather 'encryption-provider-config'.
Doc reference https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
> Fixes wrong name of the kube-apiserver flag

- KOPS.md
`apiVersion` is missed in EncryptionConfiguration
The pod contains errors preventing it to start.
> Fix kops documentation

- Dockerfile
this PR overrides #32 . the vendor directory was available but we were not using it to build.
> use vendor directory to build

- OWNERS_ALIASES
- SECURITY_CONTACTS
@gyuho is a member in good standing of the Kubernetes community and is the lead maintainer of etcd. He is also managing the encryption provider integration on EKS.
> Added Gyuho Lee as owner

- pkg/httputil/client_test.go
Workaround for flaky test "TestNewRateLimitedClient"
Asked Go team if this is an expected behavior.
ref. https://github.com/golang/go/issues/36848
ref. https://github.com/kubernetes-sigs/aws-encryption-provider/issues/61
> pkg/httputil: mask "dial i/o timeout" error in "TestNewRateLimitedClient"

- cmd/server/main.go
- pkg/healthz/healthz.go
- pkg/healthz/healthz_test.go
- pkg/plugin/metrics_test.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
gRPC server version check doesn't tell much about KMS API availability.
Adding deep health check to test `kms:Encrypt` calls.
> health check KMS API availability

- KOPS.md
- README.md
- Replacing single dash `-` with double dash `--` for arguments in example yamls to match the actual functionality.
> Double-dash(--) args in example commands

- cmd/server/main.go
- hack/verify-golint.sh
- pkg/healthz/healthz.go
- pkg/healthz/healthz_test.go
- pkg/livez/livez.go
- pkg/livez/livez_test.go
- pkg/plugin/metrics_test.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
Keep the existing `/healthz` behavior. Instead, add a new `/livez` endpoint to filter out user-induced errors (e.g., deleted CMK, revoked grant). Example healthz and livez outputs:
```
$ curl -L http://localhost:8083/healthz
KMSInvalidStateException: arn:aws:kms:us-west-2:REDACTED:key/REDACTED is pending deletion.
$ curl -L http://localhost:8083/livez
OK
```
> Add "Live" API with "/livez" endpoint to discard user-induced errors

- Dockerfile
Upgrading the image used in the Dockerfile to minimal base image
Testing:
For testing, the new image was created and built, and tested on Kubernetes versions 1.19 - 1.23.
The manifest was modified to support the newer way of using go-runner.
```
command:
- /go-runner
- --log-file=XXXXXX
- --also-stdout=false
- --redirect-stderr=true
- /aws-encryption-provider
- --region=XXXXXX
- --encryption-context=XXXXXXXX
- --key=XXXXXXXX
- --qps-limit=XXXx
- --burst-limit=XXXX
- --listen=XXXXXX
- --health-port=XXXXXX
```
> upgrading to minimal base image

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Dockerfile
This PR originally contained the full update to go 1.19, but now just adds the pieces missed in #89.
- Update golang to 1.19 in Dockerfile and GitHub workflows
- Update go-runner base image
- Update GitHub Actions versions to prepare for [removal of Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
Resolves #85
> chore: finish update to go 1.19

- pkg/server/server.go
- pkg/server/server_test.go
The existing code didn't check if the socket file exists or not. In the scenario when the file has already exists, Listen failed.
This PR adds a clean-up for the unix domain socket file before listening on it.
> add a clean-up for the unix domain socket before listen on it

- go.mod
- go.sum
**What this PR does / why we need it**:
Updates google.golang.org/protobuf to v1.33.0 to resolve CVE-2024-24786.
- Bump github.com/golang/protobuf to v1.5.4, google.golang.org/protobuf to v1.33.0
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # [CVE-2024-24786](https://github.com/advisories/GHSA-8r3f-844c-mc37)
> Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
* --skip-publish was replaced with --skip=publish
* --rm-dist was replaced with --clean
https://goreleaser.com/deprecations/#-skip
https://goreleaser.com/deprecations/#-rm-dist
This resolves the CI failure in #120
> Fix goreleaser --skip-publish flag deprecation

- pkg/kmsplugin/kms.go
- pkg/plugin/plugin_v2_test.go
Sometimes we are seeing the same error as part of 2 exceptions when using external key store. Treat both as user induced.
> Handle external keystore error as user induced

- cmd/client/main.go
- go.mod
- hack/verify-golint.sh
- pkg/connection/connection.go
- pkg/plugin/metrics_test.go
- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
- test/integration/integration_test.go
* We have been pinning to older versions of many golangci-lint packages that are no longer needed
* Updated golangci-lint to v1.61.0 and change a deprecated --deadline flag to --timeout
* Resolve linter errors - mostly this is ignoring staticcheck for deprecated KMSv1 code that's being intentionally carried
* Replace deprecated `grpc.Dial`/`grpc.DialContext` with `grpc.NewClient` https://pkg.go.dev/google.golang.org/grpc@v1.65.0#Dial
Resolves CI linting failures in #120
> Update golangci-lint to fix aws-sdk-go-v2 linting issues

- cloudbuild.yaml
PR to start publishing official aws-encryption-provider containers. Resolves #71
Followed image-pushing guide in [test-infra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md)
Utilizes existing container repo created from this [PR](https://github.com/kubernetes/k8s.io/pull/7587)
Corresponding job configuration for image pushing [PR](https://github.com/kubernetes/test-infra/pull/34772) in test-infra account
> Cloudbuild for releasing official container

- cloudbuild.yaml
Recently merged PR #136 but it leads to build failure due to invalid default IMAGE overrides passed by the build system. 
In this PR we explicitly set the IMAGE variable with the correct image name to ensure the container tag is valid.
Failing build : https://storage.googleapis.com/kubernetes-ci-logs/logs/aws-encryption-provider-push-images/1920901423042662400/build-log.txt
Failure reason:
```
docker buildx build \
--output=type=docker \
--platform=linux/amd64 \
-t us-central1-docker.pkg.dev/k8s-staging-images/aws-encryption-provider/gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250116-2a05ea7e3d:latest \
-t us-central1-docker.pkg.dev/k8s-staging-images/aws-encryption-provider/gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250116-2a05ea7e3d:v20250509-4bb7e48 \
--build-arg …
```
> fix: failing build due to invalid IMAGE override in container builds

- go.mod
- go.sum
Bumps the `github.com/aws/aws-sdk-go-v2` package to 1.39.2. This is to include endpoints for the `aws-eusc` partition.
Testing - `make test`
> Bump aws sdk go v2 package to v1.39.2
