kubernetes-sigs/aws-encryption-provider

SECURITY_CONTACTS
=> add SECURITY_CONTACTS file

OWNERS, OWNERS_ALIASES
=> update owners file

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, OWNERS_ALIASES, SECURITY_CONTACTS
* Added GitHub Issue templates
=> Updated security contacts, added micahhausler to administrator

README.md
/assign sethpollack
Resolves #9
=> Added user guide to README

cmd/server/main.go, go.mod, pkg/plugin/metrics.go, pkg/plugin/plugin.go
Added very basic metrics to the aws-encryption-provider to get sense of how many encrypt/decrypt calls are successful/failed.
=> add very basic metrics

README.md
Update documentation to reflect changes required to run aws-encryption-provider at cluster bootstrap time.
=> update documentation for bootstrap cluster time requirements

cmd/client/main.go, cmd/server/main.go, pkg/cloud/cloud.go, pkg/cloud/mock.go, pkg/plugin/plugin.go, pkg/plugin/plugin_test.go, pkg/server/server.go, pkg/version/version.go, test/integration/integration_test.go
Update the copyright year to 2020 in the code.
=> update copyright year to 2020

.travis.yml, Dockerfile, go.mod
updating the go version to 1.13
=> update go version

Dockerfile, Makefile
wihout "-w -s" ldflags:
```bash
-rwxr-xr-x    1 root     root       19.0M Jan 14 19:35 bin/aws-encryption-provider
```
with "-w -s" ldflags:
```bash
-rwxr-xr-x    1 root     root       14.2M Jan 14 19:34 bin/aws-encryption-provider
```
=> remove installsuffix cgo and add -w -s ldflags

Makefile
also update Makefile to use vendor directory for running test and building server/client image
=> make use of vendor directory consistent

Dockerfile
=> Dockerfile: build from "busybox" to include "/bin/sh"

cmd/server/main.go
To cross-check flag parsed values via CLI
Signed-off-by: Gyuho Lee <leegyuho@amazon.com>
=> cmd/server: add kms server start logging

pkg/httputil/client_test.go
The unit test written for client.go has some flaw so improved the test
=> Improving the unit tests for client_test.go

SECURITY_CONTACTS
cc @nckturner @wongma7 can you +1?
=> Removed emeritus reviewers from SECURITY_CONTACTS

go.mod, go.sum
=> update aws go SDK to 1.54.6

go.mod, go.sum
Updated upstream dependency in `go.mod` to v1.31.0
Ran `go mod tidy` to update `go.sum`
=> Update upstream dependency to v1.31.0

go.mod, go.sum
Bump dependencies for upstream release v1.32.0
=> Bump dependencies for upstream release v1.32.0

OWNERS_ALIASES
=> Adding yue9944882 to approver list

pkg/cloud/mock.go, pkg/plugin/plugin_v2.go, pkg/plugin/plugin_v2_test.go
This PR adds decryption to the KMSv2 health check API aka. "Status" API.
In the past in KMSv1, when kube-apiserver performs health check at the the plugin, it used to call both encryption and decryption API:
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go#L337-L348
While in KMSv2, kube-apiserver only calls the Status API for once. Currently the Status API only performs the encryption check. This leads to an issue that KMS provider can be healthy even if the `kms:Decrypt` permission is removed from the environment, which is misleading.
=> Add decryption to KMSv2 status health check

pkg/healthz/healthz_test.go, pkg/livez/livez_test.go, pkg/plugin/plugin.go, pkg/plugin/plugin_test.go, pkg/plugin/plugin_v2.go, pkg/plugin/plugin_v2_test.go
Exclude KMS throttling from livez check of plugins
=> Exclude KMS throttling from livez

pkg/kmsplugin/kms.go, pkg/kmsplugin/kms_test.go, pkg/livez/livez_test.go, pkg/plugin/plugin.go, pkg/plugin/plugin_v2.go, pkg/plugin/shared_health_check.go
Count context cancelled as user induced error
=> Count context cancelled as user induced
